language: objective-c

before_install:
    - npm install -g istanbul

notifications:
  email:
    on_success: never
    on_failure: change

script:
    - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
    - npm run quality
    env:
        - COVERAGE=true
    - npm run coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
