language: objective-c

before_install:
    - npm install -g istanbul
    - npm install -g jasmine-focused
    - npm install -g jshint
    - npm install -g codeclimate-test-reporter
    - npm install -g codacy-coverage

env:
    - COVERAGE=false
    - COVERAGE=true

notifications:
  email:
    on_success: never
    on_failure: change

script:
    - './test.sh'
